controllers:
  resource: ../src/Controller/
  type: attribute
tasks:
  path: /tasks
  controller: App\Controller\TaskController::index
register:
  path: /register
  controller: App\Controller\UserController::register
