controllers:
  resource: ../src/Controller/
  type: attribute
tasks:
  path: /tasks
  controller: App\Controller\TaskController::index
register:
  path: /register
  controller: App\Controller\UserController::register
login:
  path: /login
  controller: App\Controller\UserController::login
logout:
  path: /logout
index:
  path: /
  controller: App\Controller\UserController::login
